### PR TITLE
Updated deployment location to AIB location for Custom Image Build solution

### PR DESCRIPTION
**Pull request by jamasten**
- Sets most resources to deploy to the same location as the AIB image template
- Allows the primary and DR locations for the image version to be different than the AIB image template

### CODE REVIEW

**Review by shawntmeyer — COMMENTED** [review]
if I wasn't on vacation i'd try to figure this out, but I bet we can use the filter function to filter out 'global' for the primary image location and 'global' and the primary image location for secondary location.

**Comment by jamasten** [comment]
I'll take a look at it @shawntmeyer

**Comment by jamasten** [comment]
@shawntmeyer just pushed a commit that removes Global location.  Any other feedback?

**Comment by shawntmeyer** [comment]
Remove value of primary location from possible for secondary. That was fast!

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jamasten** [comment]
@shawntmeyer good call! I'll look into that too

**Comment by jamasten** [comment]
@shawntmeyer just added the fix to ensure the primary and DR locations don't match

**Review by danycontre — APPROVED** [review]

**Comment by danycontre** [comment]
@jamasten  thanks for your contribution

**Pull request merged**
