### PR TITLE
Added ZRS Locations for Image Version Replication Regions

### PR DESCRIPTION
**Pull request by jamasten**
Added a ResourceTypes API call for Microsoft.Storage to get the zone mappings for storage accounts.  If a user selects ZRS storage for the Storage Account Type input, the zone mapping locations are used for the allowed values in the drop-down menu for the Image Version's primary and DR locations.  Since the ZRS supported locations are now included, I also removed the warning boxes about selecting an appropriate location for ZRS storage.  Thank you @shawntmeyer for the help with this!!

### CODE REVIEW

**Comment by jamasten** [comment]
@danycontre, hold off on merging this PR.  Found an issue.  My build failed b/c I picked a region that didn't support ZRS.

@shawntmeyer, the zone mappings locations don't appear to be accurate.  I was able to pick West US which is not zone redundant.

**Comment by jamasten** [comment]
After comparing the [zone support doc](https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support) against the values in the drop-down menu, there appear to be two locations in the drop-down menu that don't exist in the doc: North Central US and West US.  I can attempt to manually filter these out and submit feedback to have it fixed.  What are your thoughts @danycontre & @shawntmeyer?

**Comment by jamasten** [comment]
I ran an API call in PowerShell to check the data.  So, for some reason those two locations have been added even though they have no zones. We'll have to add another filter for the zone mappings locations that don't have an array length of 3 on the zones.

location             zones
--------             -----
Australia East       {2, 3, 1}
Brazil South         {2, 3, 1}
Canada Central       {2, 3, 1}
Central India        {2, 3, 1}
Central US           {2, 3, 1}
East Asia            {2, 3, 1}
East US              {2, 3, 1}
East US 2            {2, 3, 1}
France Central       {2, 3, 1}
Germany West Central {2, 3, 1}
Japan East           {2, 3, 1}
Korea Central        {2, 3, 1}
North Central US     {}
North Europe         {2, 3, 1}
Norway East          {2, 3, 1}
Qatar Central        {2, 3, 1}
South Africa North   {2, 3, 1}
South Central US     {2, 3, 1}
Southeast Asia       {2, 3, 1}
Sweden Central       {2, 3, 1}
Switzerland North    {2, 3, 1}
UAE North            {2, 3, 1}
UK South             {2, 3, 1}
West Europe          {2, 3, 1}
West US              {}
West US 2            {2, 3, 1}
West US 3            {2, 3, 1}

**Comment by jamasten** [comment]
I added a filter to ensure each location has 3 zones which removes North Central US and West US.  All is well now so this PR is ready for review and merging.

**Comment by danycontre** [comment]
@jamasten sorry i'm late to the discussion, agree with introducing a filter to remove zones flagged as AZ capable even though they have none.

A usual thanks for your contribution.

**Comment by jamasten** [comment]
@danycontre, I’ve implemented the filter which fixes the locations.  North Central US and West US are no longer displayed in the drop down menus.  This can be merged unless there’s another problem that I missed.

**Review by danycontre — APPROVED** [review]

**Pull request merged**
