### PR TITLE
default description decorators

### PR DESCRIPTION
**Pull request by JamJarchitect**
# Overview/Summary

This PR removes the `Default: <X>` from the description decorators in both `deploy-baseline.bicep` and `deploy-custom-image.bicep`

## This PR fixes/adds/changes/removes

1. Purely documentation - as Summary

### Breaking Changes

1. N/A

## Testing Evidence

N/A

### CODE REVIEW

**Comment by danycontre** [comment]
@JamJarchitect would it be possible to add a column in the auto generated MD files to provide to point out the default value? similar to how CARML does it.

**Comment by JamJarchitect** [comment]
> @JamJarchitect would it be possible to add a column in the auto generated MD files to provide to point out the default value? similar to how CARML does it.

@danycontre

The default value is with the parameter detail underneath the table. As it's automated documentation, as far as I know the parameter detail by design sits under the table and not as a column. In my opinion this could be if the default value has a lot of context, it could potentially make the table unreadable.

We need to update the repository workflow permissions for this to fully work I believe:

image

**Comment by JamJarchitect** [comment]
PR Closed. Methods not to be used.

**Comment by danycontre** [comment]
Hey @JamJarchitect the repo has the permissions you mentioned.

**Pull request closed without merging**
