### PR TITLE
Added support for Azure US Government in Custom Image Build solution

### PR DESCRIPTION
**Pull request by jamasten**
- Added US Gov regions to location acronyms variable
- Removed DOD regions from time zones variable
- Added logic to only deploy the "Image Template Build Automation" custom role in Azure Cloud since the permissions are not supported in Azure US Government yet
- Added a "Deploy to Azure Gov" button

### CODE REVIEW

**Comment by danycontre** [comment]
@jamasten thanks for your contribution.

Went through the PR and only comment i have is:
- Should module roleAssignment_AzureUSGovernment only run if environment().name is not "AzureCloud" (aka gov deployment)?

Currently it always runs regardless of the target cloud:
//// Unique role assignment for Azure US Government since it does not support image template permissions
module roleAssignment_AzureUSGovernment '../../carml/1.2.0/Microsoft.Authorization/roleAssignments/resourceGroup/deploy.bicep' = {
    name: 'Role-Assignment_MAG_${time}'
    scope: resourceGroup(sharedServicesSubId, varResourceGroupName)
    params: {
        roleDefinitionIdOrName: 'Contributor'
        principalId: userAssignedManagedIdentity.outputs.principalId
        principalType: 'ServicePrincipal'
    }
}

Would like to get your thoughts around doing something like:
//// Unique role assignment for Azure US Government since it does not support image template permissions
module roleAssignment_AzureUSGovernment '../../carml/1.2.0/Microsoft.Authorization/roleAssignments/resourceGroup/deploy.bicep' = if (environment().name =! 'AzureCloud') {
    name: 'Role-Assignment_MAG_${time}'
    scope: resourceGroup(sharedServicesSubId, varResourceGroupName)
    params: {
        roleDefinitionIdOrName: 'Contributor'
        principalId: userAssignedManagedIdentity.outputs.principalId
        principalType: 'ServicePrincipal'
    }
}

**Review by danycontre — CHANGES_REQUESTED** [review]
@jamasten thanks for your contribution.

Went through the PR and only comment i have is:

Should module roleAssignment_AzureUSGovernment only run if environment().name is not "AzureCloud" (aka gov deployment)?
Currently it always runs regardless of the target cloud:

module roleAssignment_AzureUSGovernment '../../carml/1.2.0/Microsoft.Authorization/roleAssignments/resourceGroup/deploy.bicep' = {
}

Would like to get your thoughts around doing something like:

module roleAssignment_AzureUSGovernment '../../carml/1.2.0/Microsoft.Authorization/roleAssignments/resourceGroup/deploy.bicep' = if (environment().name =! 'AzureCloud') {
}

**Comment by jamasten** [comment]
Good catch @danycontre! I forgot the condition. Do you want me to add that and push the change?

**Comment by danycontre** [comment]
No worries, just wanted to get your thoughts, i will push it and merge it.

**Comment by jamasten** [comment]
Thank you!

**Pull request merged**
