### PR TITLE
Fix for Image Version Locations in Custom Image Build Solution

### PR DESCRIPTION
**Pull request by jamasten**
Reverting the inputs for the image version locations to prevent deployment errors.  This happens when a user fails to make the primary location unique from the DR location. We will change back to the "LocationSelector" input when it supports the "defaultValue" property. Also, updated the "defaultValue" on the DR location input to automatically change to the paired region for the primary location (if one exists).

### CODE REVIEW

**Comment by jamasten** [comment]
@shawntmeyer for your awareness.  I tried to make you a reviewer but for some reason it won't populate your name. Weird!

**Comment by jamasten** [comment]
@danycontre & @shawntmeyer, I was running a test deployment and just realized the location API call also returns logical locations.  For instance, the drop-down menu displays "Asia". That's a logical location, not physical. I need to filter those out so hold off on merging please.

**Comment by jamasten** [comment]
@danycontre & @shawntmeyer, all is well now with my PR. The locations API is only being used to set the default value on the DR location, which is now the paired region for the primary location.  The location inputs are sourced from the "Microsoft.Compute/galleries/images/versions" resourceTypes API call so the locations are all physical locations, no logical locations anymore. I ran a test deployment with no errors.  Please check it out now and let me know if anything needs to be adjusted. Thanks!

**Comment by danycontre** [comment]
@jamasten thanks for your contribution.

**Review by danycontre — APPROVED** [review]

**Pull request merged**
