### PR TITLE
added TrustedLaunch parameters to Session Host and main baseline temp…

### PR DESCRIPTION
**Pull request by shawntmeyer**
Splitting my fork into multiple branches for easier approval. Here is the result of deploying with TrustedLaunch, SecureBoot, and vTPM all enabled.
trustedlaunchproof

### CODE REVIEW

**Review by shawntmeyer — COMMENTED** [review]
I removed the avdSessionHosts prefix from the three new parameters. I also updated the portal-ui.json file to include the security profile parameters. This commit includes the contents of a PR I have in against the Microsoft.Compute/galleries/images module bicep file to include the securityType parameter. This branch does not currently include creating a V2 and TrustedLaunch custom image.

**Comment by jamasten** [comment]
@danycontre Can we hold off on merging this?  I've had a PR in limbo since 11/25 and these code changes are going to create merge conflicts.

**Comment by shawntmeyer** [comment]
> 

Hi Jason, I saw your PR. Nice work on the automation. I think we could easily work together to make both your PR and the Trusted Launch, Confidential VM, etc stuff work.

**Comment by jamasten** [comment]
Hi Shawn.  Thanks!  A lot has changed in the Custom Image Build solution, and I spent a lot of time working on it.  It would be easier to add in your updates after mine have been merged.  I would be happy to work together on it if needed. Originally, I was going to add trusted launch into my updates, but I didn't have the latest CARML code for the image definition.  Glad to see you were able to track that down.

**Comment by shawntmeyer** [comment]
Im sure we can do it. Could even have a call about it on teams soon if you want.

Sent via the Samsung Galaxy S22 Ultra 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
