### PR TITLE
avd file share backup recovery services vault

### PR DESCRIPTION
**Pull request by jegarg**

### CODE REVIEW

**Comment by jegarg** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by jegarg** [comment]
@microsoft-github-policy-service agree company = "Microsoft"

**Comment by jegarg** [comment]
@danycontre @swathibhat1

**Comment by jegarg** [comment]
@danycontre @swathibhat1 
Main branch PR created..
Kindly check and let me know if anything needs to be done

**Comment by danycontre** [comment]
@jegarg thanks for your contribution please update your fork it is 170 commits behind the main repo, we merged a big PR yesterday.

Comments:
- Pushed changes to adapt to our standards.
- Please make sure all parameters have a description.
- CARML 1.3.0 module you copied to use with Azure ASR has errors calling some other modules, please check that the path are right.
- Tagging seems to be missing.
- We need to add all portal UI definitions for this new feature, including backupVaultCustomNaming to portal UI custom naming section.
- Does the code have options to use existing: recovery vault, policy?

Please check the changes and let us know your comments, more changes/updates are needed, please confirm once your fork has been synced with main so we can continue checking and run tests.

**Comment by jegarg** [comment]
Sure @danycontre 
Would do the changes and remove the errors from the CARML Module. I didn't copy the complete RSV Module, just the ones I have used, that's why its throwing errors.

**Comment by danycontre** [comment]
Let's copy all the resource provider, will continue to check the code.

Thanks again for your contribution.

**Comment by jegarg** [comment]
We need to add all portal UI definitions for this new feature, including backupVaultCustomNaming to portal UI custom naming section.

Can you explain this one?

**Comment by jegarg** [comment]
- Pushed changes to adapt to our standards.
- Please make sure all parameters have a description. - _Done_
- CARML 1.3.0 module you copied to use with Azure ASR has errors calling some other modules, please check that the path are right. - _copied all the resource providers_
- Tagging seems to be missing. - _added_
- We need to add all portal UI definitions for this new feature, including backupVaultCustomNaming to portal UI custom naming section. _???? please explain_
- Does the code have options to use existing: recovery vault, policy? _yes, in the module_

**Comment by jegarg** [comment]
@danycontre

**Comment by danycontre** [comment]
Thanks for the updates Jeet, checking...

**Pull request closed without merging**
